package com.parser;

import java.util.Scanner;

public class ParserDriver
{
    public static void main(String args[])
    {
        Scanner s = new Scanner(System.in);
        System.out.println("~~~~~TESTING~~~~~");
        System.out.print("Enter a filename: ");
        String input = s.next();
        System.out.println("");
        Parser parser = new Parser(input);
        Parser parser2 = new Parser(input);
        //System.out.println(parser.getSymbolTable().toString());
        try
        {
            parser.parseProgram();
            parser2.parseProgram();
            System.out.println("~~PARSER OUTPUT~~");
            System.out.println("Valid Program!");
            System.out.println("FILENAME: " + input);
            System.out.println("SYMBOL TABLE: " + parser.getByteInterpreter().getSymbolTable());
            System.out.println("GENERATED BYTECODE: " + parser.getByteInterpreter().getByteCode());
            System.out.println("MEMORY: " + parser.getByteInterpreter().getMemory());
            System.out.println("");

            //testing equals method
            System.out.println("parser = parser2: " + parser.equals(parser2));

            //toString method
            System.out.println(parser.toString());
        }
        catch(Exception e)
        {
            System.out.println(e.toString());
            //e.printStackTrace();
        }
    }
}
